name: "Publish a new release draft"

on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      ref:
        description: 'Branch or tag to build e.g. main or v0.1.0'
        required: true
        type: string
        default: 'main'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref || 'main' }}
      
      - name: Setup rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Get version
        id: get_version
        run: echo "VERSION=$(cargo read-manifest --frozen | jq -r '.version')" >> $GITHUB_OUTPUT
  
  build-linux:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{inputs.ref || 'main'}}
      
      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - name: Running test suite
        run: cargo test --release

      - name: Build project
        run: cargo build --release

      - name: Create a new release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{secrets.GITHUB_TOKEN}}
          release-type: rust
      
