name: "Test Suite"

on: 
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      
      - name: Running test suite
        run: cargo test --release
      
